services:
  db:
    image: postgres:16
    container_name: postgres_db_csc
    volumes:
      - postgres_data_csc:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

volumes:
  postgres_data_csc: